name: jenkins-status-indicator # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2plugs' # just for humans, typically '1.2+git' or '1.3.2'
summary: jenkins-status-indicator # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

architectures:
  # - build-on: amd64
  - build-on: armhf
  # - build-on: arm64
  # - build-on: s390x
  # - build-on: ppcel64

parts:
  jenkins-status-indicator:
    # See 'snapcraft plugins'
    plugin: nodejs
    source: .
    nodejs-version: 14.7.0
    nodejs-package-manager: yarn
    stage-packages:
      - libatomic1
    build-packages:
      - make
      - g++

apps:
  jenkins-status-indicator:
    command: jenkins-status-indicator
    plugs:
      - gpio
      - network
      - network-bind
